version: 2.1

jobs:
  build-geth:
    docker:
      - image: cimg/go:1.21
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: go run build/ci.go install
  unit-test:
    resource_class: large
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          command: go run build/ci.go test
  lint-geth:
    resource_class: medium
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          command: go run build/ci.go lint


workflows:
  main:
    jobs:
      - build-geth:
          name: Build geth
      - unit-test:
          name: Run unit tests for geth
      - lint-geth:
          name: Run linter over geth
