name: "[cLabs] Publish Docker Image For Release"

on:
  workflow_dispatch:
  release:
    types: [published]  # Trigger the workflow only when a release is published

jobs:
  Build-Container-Release:
    runs-on: ['self-hosted', 'org', 'ubuntu-22-04']
    permissions:
      contents: write
      actions: read
      pull-requests: write
      security-events: write
      attestations: write
      id-token: write
    concurrency:
      group:   ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Determine Tags
        id: determine_tags
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [[ "$TAG" == *"rc"* || "$TAG" == *"beta"* || "$TAG" == *"alpha"* ]]; then
            echo "TAGS=$TAG" >> $GITHUB_ENV
          else
            echo "TAGS=$TAG,stable,latest" >> $GITHUB_ENV
          fi

          echo "Tags for container: $TAGS"

      - name: Build and Push
        uses: celo-org/reusable-workflows/.github/workflows/docker-build.yaml@v3.0.0-alpha
        with:
          workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-op-geth-release/providers/github-by-repos
          service-account: op-geth-release@blockchaintestsglobaltestnet.iam.gserviceaccount.com
          artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-geth
          tags: celo-v0.0.0-ci-test #debug tag for ci test  - "${{ env.TAGS }}"
          context: .
