name: "[cLabs] Publish Docker Image For Release"

on:
  workflow_dispatch:
  release:
    types: [published]  # Trigger the workflow only when a release is published

jobs:
  Build-Container-Release:
    permissions:
      contents: write
      actions: read
      pull-requests: write
      security-events: write
      attestations: write
      id-token: write
    concurrency:
      group:   ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    uses: celo-org/reusable-workflows/.github/workflows/docker-build.yaml@v3.0.0-alpha
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-op-geth-release/providers/github-by-repos
      service-account: op-geth-release@blockchaintestsglobaltestnet.iam.gserviceaccount.com
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-geth
      tags: ${{ github.event.release.tag_name }},latest,stable
      context: .
      debug_enabled: false
