name: Docker Build Push
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-scan-container-geth:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@main
    name: Build us-west1-docker.pkg.dev/blockchaintestsglobaltestnet/dev-images/op-geth:${{ github.sha }}
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-op-geth/providers/github-by-repos
      service-account: 'op-geth-dev@blockchaintestsglobaltestnet.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/blockchaintestsglobaltestnet/dev-images/op-geth
      tags: ${{ github.sha }}
      platforms: linux/amd64,linux/arm64
      context: .
      file: Dockerfile
      trivy: true

  build-scan-container-bootnode:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@main
    name: Build us-west1-docker.pkg.dev/blockchaintestsglobaltestnet/dev-images/op-geth-bootnode:${{ github.sha }}
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-op-geth/providers/github-by-repos
      service-account: 'op-geth-dev@blockchaintestsglobaltestnet.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/blockchaintestsglobaltestnet/dev-images/op-geth-bootnode
      tags: ${{ github.sha }}
      platforms: linux/amd64,linux/arm64
      context: .
      file: Dockerfile.bootnode
      trivy: true
